# -*- coding: utf-8 -*-
"""test_virtualcolumn.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hhhvquf5uWHEx0ZBMkAtHCZ1iAhzZ2jU
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile test_virtualcolumn.py
# import pandas as pd
# from solution import add_virtual_column
# 
# def test_sum_of_two_columns():
#     df = pd.DataFrame([[1, 1]] * 2, columns = ["label_one", "label_two"])
#     df_expected = pd.DataFrame([[1, 1, 2]] * 2, columns = ["label_one", "label_two", "label_three"])
#     df_result = add_virtual_column(df, "label_one+label_two", "label_three")
#     assert df_result.equals(df_expected), "Sum test failed"
# 
# def test_multiplication_of_two_columns():
#     df = pd.DataFrame([[1, 1]] * 2, columns = ["label_one", "label_two"])
#     df_expected = pd.DataFrame([[1, 1, 1]] * 2, columns = ["label_one", "label_two", "label_three"])
#     df_result = add_virtual_column(df, "label_one * label_two", "label_three")
#     assert df_result.equals(df_expected), "Multiplication test failed"
# 
# def test_subtraction_of_two_columns():
#     df = pd.DataFrame([[1, 1]] * 2, columns = ["label_one", "label_two"])
#     df_expected = pd.DataFrame([[1, 1, 0]] * 2, columns = ["label_one", "label_two", "label_three"])
#     df_result = add_virtual_column(df, "label_one - label_two", "label_three")
#     assert df_result.equals(df_expected), "Subtraction test failed"
# 
# def test_empty_result_when_invalid_labels():
#     df = pd.DataFrame([[1, 2]] * 3, columns = ["label_one", "label_two"])
#     df_result = add_virtual_column(df, "label_one + label_two", "label3")
#     assert df_result.empty, "Invalid column name test failed"
# 
# def test_empty_result_when_invalid_rules():
#     df = pd.DataFrame([[1, 1]] * 2, columns = ["label_one", "label_two"])
#     df_result = add_virtual_column(df, "label_one \\ label_two", "label_three")
#     assert df_result.empty, "Invalid character test failed"
# 
# def run_all_tests():
#     test_sum_of_two_columns()
#     test_multiplication_of_two_columns()
#     test_subtraction_of_two_columns()
#     test_empty_result_when_invalid_labels()
#     test_empty_result_when_invalid_rules()
#     print("✅ Wszystkie testy przeszły pomyślnie!")
# 
# run_all_tests()
#
